### PR TITLE
COMPLETE PASSWORD GENERATION USECASE | TESTED AT 100% CODE COVERAGE | FINAL PROJECT PR

### LINKED ISSUE #8: Add random password generator to create true-random secure passwords
## User Story
As a user, I want a random password generator to help me come up with secure, true-random passwords generated from atmospheric data so that I know this password is as secure as possible. 

## User Interactions

### PR DESCRIPTION
**Pull request by saeedshrouf**
Closes #8 

{AFA685E8-4039-4FB7-A721-65A9A049B924}

### CODE REVIEW

**Comment by HACKERALERT** [comment]
(reopened so we can see the checks run again)

**Review by hydrabeer — APPROVED** [review]
**LGTM**

**Review by 9naama — APPROVED** [review]
LGTM

**Review by HACKERALERT — APPROVED** [review]
🥳

**Pull request merged**
