### PR TITLE
Create CryptoAdapter.java and tests

### PR DESCRIPTION
**Pull request by HACKERALERT**
Adds basic getRandomBytes and deriveKey crypto operations. More functions related to encryption/decryption will need to be implemented later, but for now, these two are implemented and have tests with them ready to merge and add basic folder structure to the project.

### CODE REVIEW

**Comment by HACKERALERT** [comment]
Converting to draft as I will work to implement CA with an interface and implement it with Argon2.

**Comment by HACKERALERT** [comment]
review again plz

**Review by hydrabeer — APPROVED** [review]
LGTM

**Comment by HACKERALERT** [comment]
🙏

**Pull request merged**
